leftnav:
- identifier: fbf4ff68-5623-9521-a45c-1bbe49a17f07
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 1a34af78-c327-f895-f8f9-c67e299d87ca
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: ddae6b41-d1f7-a146-cf2e-64e14e253c13
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b7736a68-9e5b-fc5e-bf64-8a79f799b258
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 797be95d-5c75-92eb-695a-7010808622a5
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 50
